/**
 * Truncate text to a maximum number of Unicode characters.
 * Returns an empty string when the input is nullish or empty.
 */
export function truncate(text: string | undefined | null, maxLen: number): string {
  if (text === undefined || text === null) {
    return '';
  }
  if (text.length <= maxLen) {
    return text;
  }
  return text.slice(0, maxLen);
}

/**
 * Resolve the locale used for AI audit log reporting.
 *
 * The deployment environment variable `OSS_LANG` (underscore form, e.g.
 * `zh_CN`, `en_US`) takes precedence so that audit log language is decided by
 * the deployment, not by the per-request frontend locale. When `OSS_LANG` is
 * unset, the request locale (`command.locale`) is used as a fallback so that
 * local development without the env var keeps working.
 */
export function resolveAuditLocale(envValue: string | undefined, fallback: string): string {
  if (envValue === undefined || envValue.trim() === '') {
    return fallback;
  }
  return envValue.trim().replace(/_/gu, '-');
}

/**
 * Build the "accessed resource name" string from a de-duplicated list of
 * model ids and km markers, using the locale-appropriate separator.
 *
 * Chinese locale uses `；`, English locale uses `; `.
 * Returns an empty string when the list is empty.
 */
export function buildResourceName(items: readonly string[], locale: string): string {
  if (items.length === 0) {
    return '';
  }
  const separator = locale === 'zh-CN' ? '；' : '; ';
  return items.join(separator);
}

const detailTemplateZh =
  '创建对话资源访问详情：\n对话id：%s；\n事件类型：sys_input_output；\n被访问的资源名称：%s；\n系统接收的输入内容：%s；\n系统产生的输出内容：%s';

const detailTemplateEn =
  'Create chat resource access details:\nchat id: %s;\nevent type: sys_input_output;\nname of the accessed resource: %s;\ninput received by the system: %s;\noutput generated by the system: %s';

/**
 * Format the AI log `detail` field by selecting the locale-appropriate
 * template and filling the 4 positional `%s` placeholders:
 * 1. chatId (session id)
 * 2. resourceName (model names + km marker)
 * 3. question (user input, not truncated)
 * 4. answer (assistant output, already truncated by caller)
 */
export function formatAiLogDetail(locale: string, chatId: string, resourceName: string, question: string, answer: string): string {
  const template = locale === 'zh-CN' ? detailTemplateZh : detailTemplateEn;
  const parts = template.split('%s');
  return parts[0]! + chatId + parts[1]! + resourceName + parts[2]! + question + parts[3]! + answer + parts[4]!;
}
