import { describe, expect, it } from 'vitest';
import { buildResourceName, formatAiLogDetail, resolveAuditLocale, truncate } from '../src/composition/ai-log-helpers.js';

describe('truncate', () => {
  it('returns empty string for nullish input', () => {
    expect(truncate(undefined, 10)).toBe('');
    expect(truncate(null, 10)).toBe('');
  });

  it('returns original text when within limit', () => {
    expect(truncate('hello', 10)).toBe('hello');
  });

  it('truncates to maxLen Unicode characters', () => {
    expect(truncate('abcdefghij', 5)).toBe('abcde');
  });

  it('truncates multi-byte text by character count not bytes', () => {
    const text = '你好世界你好世界';
    expect(truncate(text, 4)).toBe('你好世界');
  });

  it('returns empty string for empty input', () => {
    expect(truncate('', 10)).toBe('');
  });
});

describe('buildResourceName', () => {
  it('returns empty string for empty list', () => {
    expect(buildResourceName([], 'zh-CN')).toBe('');
  });

  it('joins items with Chinese separator for zh-CN', () => {
    expect(buildResourceName(['gpt-4', 'qwen-72b', 'km'], 'zh-CN')).toBe('gpt-4；qwen-72b；km');
  });

  it('joins items with English separator for en-US', () => {
    expect(buildResourceName(['gpt-4', 'qwen-72b', 'km'], 'en-US')).toBe('gpt-4; qwen-72b; km');
  });

  it('returns single item without separator', () => {
    expect(buildResourceName(['gpt-4'], 'zh-CN')).toBe('gpt-4');
  });
});

describe('formatAiLogDetail', () => {
  const chatId = 'sess_abc123';
  const resourceNameZh = 'gpt-4；qwen-72b；km';
  const resourceNameEn = 'gpt-4; qwen-72b; km';
  const question = '怎么排查5G基站告警？';
  const answer = '5G基站告警排查步骤如下：首先检查告警级别';

  it('fills Chinese template with Chinese punctuation', () => {
    const result = formatAiLogDetail('zh-CN', chatId, resourceNameZh, question, answer);
    expect(result).toContain('创建对话资源访问详情：');
    expect(result).toContain('对话id：sess_abc123；');
    expect(result).toContain('事件类型：sys_input_output；');
    expect(result).toContain('被访问的资源名称：gpt-4；qwen-72b；km；');
    expect(result).toContain('系统接收的输入内容：怎么排查5G基站告警？；');
    expect(result).toContain('系统产生的输出内容：5G基站告警排查步骤如下：首先检查告警级别');
    expect(result).toContain('\n');
  });

  it('fills English template with English punctuation', () => {
    const result = formatAiLogDetail('en-US', chatId, resourceNameEn, question, answer);
    expect(result).toContain('Create chat resource access details:');
    expect(result).toContain('chat id: sess_abc123;');
    expect(result).toContain('event type: sys_input_output;');
    expect(result).toContain('name of the accessed resource: gpt-4; qwen-72b; km;');
    expect(result).toContain('input received by the system: 怎么排查5G基站告警？;');
    expect(result).toContain('output generated by the system: 5G基站告警排查步骤如下：首先检查告警级别');
  });

  it('handles empty resourceName', () => {
    const result = formatAiLogDetail('zh-CN', chatId, '', question, answer);
    expect(result).toContain('被访问的资源名称：；');
  });

  it('handles empty answer', () => {
    const result = formatAiLogDetail('zh-CN', chatId, resourceNameZh, question, '');
    expect(result).toContain('系统产生的输出内容：');
  });
});

describe('resolveAuditLocale', () => {
  it('returns fallback when envValue is undefined', () => {
    expect(resolveAuditLocale(undefined, 'zh-CN')).toBe('zh-CN');
  });

  it('returns fallback when envValue is empty string', () => {
    expect(resolveAuditLocale('', 'zh-CN')).toBe('zh-CN');
  });

  it('returns fallback when envValue is whitespace only', () => {
    expect(resolveAuditLocale('   ', 'en-US')).toBe('en-US');
  });

  it('takes precedence over fallback when set', () => {
    expect(resolveAuditLocale('en_US', 'zh-CN')).toBe('en-US');
  });

  it('normalizes underscore separator to hyphen', () => {
    expect(resolveAuditLocale('zh_CN', 'en-US')).toBe('zh-CN');
  });

  it('trims surrounding whitespace from envValue', () => {
    expect(resolveAuditLocale('  en_US  ', 'zh-CN')).toBe('en-US');
  });

  it('passes through already-hyphenated locale', () => {
    expect(resolveAuditLocale('en-US', 'zh-CN')).toBe('en-US');
  });
});
