---
swagger: "2.0"
info:
  version: "v1"
  title: "unifieddataservice"
  description: "LUI工参数据通用查询接口"
schemes:
  - "https"
basePath: "/rest/oss/inner/unifieddata"
x-alias: EngineerParamService
paths:
  /engineerparam:
    post:
      x-iftype: ir
      summary: "Query engineering parameter data"
      description: "Query engineering parameter data by dimension, rat type, fields and filters"
      tags:
        - "EngineerParamService"
      operationId: "queryEngineerParam"
      x-filetransfertype: NA
      x-audit:
        level: MINOR
        alwayslog: true
        operation:
          zh: '查询工参数据'
          en: 'Query engineering parameter data'
        target:
          zh: '查询工参数据'
          en: 'Query engineering parameter data'
      consumes:
        - "application/json"
      produces:
        - "application/json"
      x-annotations:
        - name: "StreamTimeout(660000)"
          schema:
            $ref: "#/definitions/StreamTimeout"
      x-exceptions:
        - name: "ServiceException"
          schema:
            $ref: "#/definitions/ServiceException"
      parameters:
        - name: "engineerParamQueryReq"
          in: "body"
          required: true
          description: "工参查询请求体"
          schema:
            $ref: "#/definitions/EpQueryRequestBody"
          x-wsf-pattern:
            - XSS_ATTACK_VALIDATOR
            - SQL_ATTACK_VALIDATOR
      responses:
        "200":
          description: "工参查询结果"
          schema:
            $ref: "#/definitions/EpQueryResponseBody"
        500:
          description: "默认ServiceException异常码，应用内部错误"
definitions:
  ServiceException:
    type: "object"
    x-ref-external: "com.huawei.bsp.remoteservice.exception.ServiceException"
  EpQueryResponseBody:
    type: "object"
    x-ref-external: "com.huawei.oss.wireless.unifieddataservice.model.EpQueryResponseBody"
  StreamTimeout:
    type: "object"
    x-ref-external: "com.huawei.maos.commons.rpc.annotation.StreamTimeout"
  MediaType:
    type: "object"
    x-ref-external: "jakarta.ws.rs.core.MediaType"
  JsonInBody:
    type: "object"
    x-ref-external: "com.huawei.maos.commons.rpc.annotation.JsonInBody"
  EpQueryRequestBody:
    type: "object"
    x-ref-external: "com.huawei.oss.wireless.unifieddataservice.model.EpQueryRequestBody"
